server:
  port: 8085

spring:
  application:
    name: question-bank-service

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb?stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: redis-password
      timeout: 2000
      database: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    enabled: true
  show-actuator: false

logging:
  level:
    org.springdoc: DEBUG
    io.swagger.v3: DEBUG
    org.springframework.web: DEBUG